### ISSUE TITLE
Large volume of requests may result in a ban

### ISSUE THREAD

**Issue by yama-yeah** [dsdanielpark/Bard-API#34]
I was throwing a request to Bard to summarize a paper, and it started throwing Response Error halfway through. This happens regardless of the Token and will not accept requests from python.
Requests from web browsers are successfully accepted, so there may be some way to fix this.
Do you have any ideas?
```
Response Error: b')]}\'\n\n38\n[["wrb.fr",null,null,null,null,[8]]]\n55\n[["di",90],["af.httprm",89,"-5846312931853295462",1]]\n25\n[["e",4,null,null,130]]\n'.
```

**Comment by dsdanielpark** [comment]
Is it correct that you have confirmed that responses are generated for short texts like "hi"?
For testing, try passing a generous timeout value to the Bard class. 
```python
Bard(timeout=200).get_answer("large Input text ")
```

**Comment by yama-yeah** [comment]
No I think it has to do with the total amount sent from python so far, not the length.
I used to be able to communicate with bard normally, but suddenly they started sending back only Response Error.
I have the Timeout set to 512 and I get a ResponseError immediately.

**Comment by yama-yeah** [comment]
```
from bardapi import Bard
import os
import requests
import os
os.environ['_BARD_API_KEY']="MyToken"

session = requests.Session()
session.headers = {
            "Host": "bard.google.com",
            "X-Same-Domain": "1",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36",
            "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
            "Origin": "https://bard.google.com",
            "Referer": "https://bard.google.com/",
        }
session.cookies.set("__Secure-1PSID", os.getenv("_BARD_API_KEY")) 
# session.cookies.set("__Secure-1PSID", token) 

bard = Bard(session=session, timeout=512)

# Continued conversation without set new session
bard.get_answer("hello")['content']
```

**Comment by yama-yeah** [comment]
One thing I do know is that if I run this on another computer, the error goes away.
Maybe it is restricted by IP address.

**Comment by dsdanielpark** [comment]
> One thing I do know is that if I run this on another computer, the error goes away. Maybe it is restricted by IP address.

Recently, I confirmed that the cookie value is initialized even during use, and added it to the readme. Isn't the cookie value initialized during use?

It is unlikely that your IP is blocked. Because if the IP is blocked, you should not receive a proper response even on the web.

**Comment by dsdanielpark** [comment]
The issue has been resolved, so I'm closing it. If you happen to identify the exact cause, I would appreciate it if you could share it. Thank you.

**Comment by yama-yeah** [comment]
Only the computer was changed and the cookie values were executed identically. The Response Error still occurs there.
After about 10 hours from the time the Response Error was confirmed, I ran the program again from the same computer, and the conversation succeeded even with the same cookie.
Frequency may have something to do with it.

**Comment by mrkeyiano** [comment]
I think the token expires, i got this same error but i visited the bard website and saw a new token and used it.

**Comment by erickythierry** [comment]
> I think the token expires, i got this same error but i visited the bard website and saw a new token and used it.

I also saw that the token changes constantly. it would be interesting if we develop a way to update the token whenever it changes

**Comment by dsdanielpark** [comment]
As the frequency of cookie changes has increased, we are currently working on accepting the following pull request for the task.

#12

**Comment by javieranton-zz** [comment]
The cookie is ok for 2 weeks, even when it changes via browser. Calling it too much and too frequently will result in a temporary ban
